/*
 * Manager+Agents API
 * Signiant Manager+Agents provides a REST API to automate user management, user group, agent groups, jobs, resource controls, and job groups. 
 *
 * OpenAPI spec version: 14.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ManageragentsApi) {
      root.ManageragentsApi = {};
    }
    root.ManageragentsApi.FileLog = factory(root.ManageragentsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The FileLog model module.
   * @module model/FileLog
   * @version 14.1.0
   */

  /**
   * Constructs a new <code>FileLog</code>.
   * @alias module:model/FileLog
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>FileLog</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FileLog} obj Optional instance to populate.
   * @return {module:model/FileLog} The populated <code>FileLog</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
      if (data.hasOwnProperty('deliveryRecords'))
        obj.deliveryRecords = ApiClient.convertToType(data['deliveryRecords'], 'Number');
      if (data.hasOwnProperty('validCount'))
        obj.validCount = ApiClient.convertToType(data['validCount'], 'Number');
      if (data.hasOwnProperty('certifiedCount'))
        obj.certifiedCount = ApiClient.convertToType(data['certifiedCount'], 'Number');
      if (data.hasOwnProperty('fileLog'))
        obj.fileLog = ApiClient.convertToType(data['fileLog'], Object);
    }
    return obj;
  }

  /**
   * @member {Number} total
   */
  exports.prototype.total = undefined;

  /**
   * @member {Number} deliveryRecords
   */
  exports.prototype.deliveryRecords = undefined;

  /**
   * @member {Number} validCount
   */
  exports.prototype.validCount = undefined;

  /**
   * @member {Number} certifiedCount
   */
  exports.prototype.certifiedCount = undefined;

  /**
   * @member {Object} fileLog
   */
  exports.prototype.fileLog = undefined;


  return exports;

}));
