/*
 * Manager+Agents API
 * Signiant Manager+Agents provides a REST API to automate user management, user group, agent groups, jobs, resource controls, and job groups. 
 *
 * OpenAPI spec version: 14.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ManageragentsApi) {
      root.ManageragentsApi = {};
    }
    root.ManageragentsApi.GetAgentGroupsObject = factory(root.ManageragentsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The GetAgentGroupsObject model module.
   * @module model/GetAgentGroupsObject
   * @version 14.1.0
   */

  /**
   * Constructs a new <code>GetAgentGroupsObject</code>.
   * A Manager agent group.
   * @alias module:model/GetAgentGroupsObject
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>GetAgentGroupsObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetAgentGroupsObject} obj Optional instance to populate.
   * @return {module:model/GetAgentGroupsObject} The populated <code>GetAgentGroupsObject</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('groupName'))
        obj.groupName = ApiClient.convertToType(data['groupName'], 'String');
      if (data.hasOwnProperty('fields'))
        obj.fields = ApiClient.convertToType(data['fields'], Object);
    }
    return obj;
  }

  /**
   * The agent group id.
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * The agent group name.
   * @member {String} groupName
   */
  exports.prototype.groupName = undefined;

  /**
   * The agent group fields.
   * @member {Object} fields
   */
  exports.prototype.fields = undefined;


  return exports;

}));
