/*
 * Manager+Agents API
 * Signiant Manager+Agents provides a REST API to automate user management, user group, agent groups, jobs, resource controls, and job groups. 
 *
 * OpenAPI spec version: 14.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ManageragentsApi) {
      root.ManageragentsApi = {};
    }
    root.ManageragentsApi.Members = factory(root.ManageragentsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Members model module.
   * @module model/Members
   * @version 14.1.0
   */

  /**
   * Constructs a new <code>Members</code>.
   * Agent group members
   * @alias module:model/Members
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Members</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Members} obj Optional instance to populate.
   * @return {module:model/Members} The populated <code>Members</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], Object);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('organization'))
        obj.organization = ApiClient.convertToType(data['organization'], 'String');
      if (data.hasOwnProperty('loadBalanceMember'))
        obj.loadBalanceMember = ApiClient.convertToType(data['loadBalanceMember'], 'Boolean');
    }
    return obj;
  }

  /**
   * The Agent group member URL
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * The agent group member type. can be `AGENT` or `HOST`
   * @member {Object} type
   */
  exports.prototype.type = undefined;

  /**
   * The agent group member description
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * The agent group member organization
   * @member {String} organization
   */
  exports.prototype.organization = undefined;

  /**
   * Load balance this member with other Agents in the group
   * @member {Boolean} loadBalanceMember
   */
  exports.prototype.loadBalanceMember = undefined;


  return exports;

}));
