/*
 * Manager+Agents API
 * Signiant Manager+Agents provides a REST API to automate user management, user group, agent groups, jobs, resource controls, and job groups. 
 *
 * OpenAPI spec version: 14.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AddAgentGroupMembers', 'model/RemoveAgentGroupMembers'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AddAgentGroupMembers'), require('./RemoveAgentGroupMembers'));
  } else {
    // Browser globals (root is window)
    if (!root.ManageragentsApi) {
      root.ManageragentsApi = {};
    }
    root.ManageragentsApi.PutAgentGroupsObject = factory(root.ManageragentsApi.ApiClient, root.ManageragentsApi.AddAgentGroupMembers, root.ManageragentsApi.RemoveAgentGroupMembers);
  }
}(this, function(ApiClient, AddAgentGroupMembers, RemoveAgentGroupMembers) {
  'use strict';

  /**
   * The PutAgentGroupsObject model module.
   * @module model/PutAgentGroupsObject
   * @version 14.1.0
   */

  /**
   * Constructs a new <code>PutAgentGroupsObject</code>.
   * A Manager Agent group.
   * @alias module:model/PutAgentGroupsObject
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PutAgentGroupsObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutAgentGroupsObject} obj Optional instance to populate.
   * @return {module:model/PutAgentGroupsObject} The populated <code>PutAgentGroupsObject</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('groupName'))
        obj.groupName = ApiClient.convertToType(data['groupName'], 'String');
      if (data.hasOwnProperty('addedMembers'))
        obj.addedMembers = ApiClient.convertToType(data['addedMembers'], [AddAgentGroupMembers]);
      if (data.hasOwnProperty('removedMembers'))
        obj.removedMembers = ApiClient.convertToType(data['removedMembers'], [RemoveAgentGroupMembers]);
      if (data.hasOwnProperty('fields'))
        obj.fields = ApiClient.convertToType(data['fields'], Object);
    }
    return obj;
  }

  /**
   * The Agent group id.
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * The Agent group name.
   * @member {String} groupName
   */
  exports.prototype.groupName = undefined;

  /**
   * Agents to be added to the group
   * @member {Array.<module:model/AddAgentGroupMembers>} addedMembers
   */
  exports.prototype.addedMembers = undefined;

  /**
   * Agents to be removed from the group
   * @member {Array.<module:model/RemoveAgentGroupMembers>} removedMembers
   */
  exports.prototype.removedMembers = undefined;

  /**
   * The Agent group fields.
   * @member {Object} fields
   */
  exports.prototype.fields = undefined;


  return exports;

}));
