/*
 * Manager+Agents API
 * Signiant Manager+Agents provides a REST API to automate user management, user group, agent groups, jobs, resource controls, and job groups. 
 *
 * OpenAPI spec version: 14.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ManageragentsApi) {
      root.ManageragentsApi = {};
    }
    root.ManageragentsApi.Relays = factory(root.ManageragentsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Relays model module.
   * @module model/Relays
   * @version 14.1.0
   */

  /**
   * Constructs a new <code>Relays</code>.
   * An agent group relays.
   * @alias module:model/Relays
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Relays</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Relays} obj Optional instance to populate.
   * @return {module:model/Relays} The populated <code>Relays</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], 'String');
      if (data.hasOwnProperty('udpPort'))
        obj.udpPort = ApiClient.convertToType(data['udpPort'], 'Number');
      if (data.hasOwnProperty('tcpPort'))
        obj.tcpPort = ApiClient.convertToType(data['tcpPort'], 'Number');
      if (data.hasOwnProperty('httpPort'))
        obj.httpPort = ApiClient.convertToType(data['httpPort'], 'Number');
    }
    return obj;
  }

  /**
   * An agent group relay address
   * @member {String} address
   */
  exports.prototype.address = undefined;

  /**
   * The udp port of the relay
   * @member {Number} udpPort
   */
  exports.prototype.udpPort = undefined;

  /**
   * The tcp port of the relay
   * @member {Number} tcpPort
   */
  exports.prototype.tcpPort = undefined;

  /**
   * The http port of the relay
   * @member {Number} httpPort
   */
  exports.prototype.httpPort = undefined;


  return exports;

}));
