/*
 * Manager+Agents API
 * Signiant Manager+Agents provides a REST API to automate user management, user group, agent groups, jobs, resource controls, and job groups. 
 *
 * OpenAPI spec version: 14.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ManageragentsApi);
  }
}(this, function(expect, ManageragentsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AccessAcls', function() {
      beforeEach(function() {
        instance = new ManageragentsApi.AccessAcls();
      });

      it('should create an instance of AccessAcls', function() {
        // TODO: update the code to test AccessAcls
        expect(instance).to.be.a(ManageragentsApi.AccessAcls);
      });

      it('should have the property edit (base name: "edit")', function() {
        // TODO: update the code to test the property edit
        expect(instance).to.have.property('edit');
        // expect(instance.edit).to.be(expectedValueLiteral);
      });

      it('should have the property execute (base name: "execute")', function() {
        // TODO: update the code to test the property execute
        expect(instance).to.have.property('execute');
        // expect(instance.execute).to.be(expectedValueLiteral);
      });

      it('should have the property read (base name: "read")', function() {
        // TODO: update the code to test the property read
        expect(instance).to.have.property('read');
        // expect(instance.read).to.be(expectedValueLiteral);
      });

      it('should have the property remove (base name: "remove")', function() {
        // TODO: update the code to test the property remove
        expect(instance).to.have.property('remove');
        // expect(instance.remove).to.be(expectedValueLiteral);
      });

      it('should have the property userName (base name: "userName")', function() {
        // TODO: update the code to test the property userName
        expect(instance).to.have.property('userName');
        // expect(instance.userName).to.be(expectedValueLiteral);
      });

    });
  });

}));
