/*
 * Manager+Agents API
 * Signiant Manager+Agents provides a REST API to automate user management, user group, agent groups, jobs, resource controls, and job groups. 
 *
 * OpenAPI spec version: 14.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ManageragentsApi);
  }
}(this, function(expect, ManageragentsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ManageragentsApi.AgentsApi();
  });

  describe('(package)', function() {
    describe('AgentsApi', function() {
      describe('getAgent', function() {
        it('should call getAgent successfully', function(done) {
          // TODO: uncomment, update parameter values for getAgent call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";

          instance.getAgent(username, password, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.Agents);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('revokeCertificate', function() {
        it('should call revokeCertificate successfully', function(done) {
          // TODO: uncomment, update parameter values for revokeCertificate call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var requestBody = new ManageragentsApi.RevokeAgentCertificate();
          requestBody.agentName = "agent.example.com";
          requestBody.caPassphrase = "********";

          instance.revokeCertificate(username, password, requestBody, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.Success);
            expect(data.success).to.be.a('string');
            expect(data.success).to.be("true");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
