/*
 * Manager+Agents API
 * Signiant Manager+Agents provides a REST API to automate user management, user group, agent groups, jobs, resource controls, and job groups. 
 *
 * OpenAPI spec version: 14.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ManageragentsApi);
  }
}(this, function(expect, ManageragentsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ManageragentsApi.JobGroupsApi();
  });

  describe('(package)', function() {
    describe('JobGroupsApi', function() {
      describe('createJobGroup', function() {
        it('should call createJobGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for createJobGroup call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var opts = {};
          opts.jobGroup = new ManageragentsApi.JobGroup();

          instance.createJobGroup(username, password, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.CreateJobGroupResponse);
            expect(data.creator).to.be.a('string');
            expect(data.creator).to.be("user1");
            {
              let dataCtr = data.jobGroups;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Object);
                expect(data).to.be();
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteJobGroup', function() {
        it('should call deleteJobGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteJobGroup call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var jobgroupnamejobgroupID = "jobgroupnamejobgroupID_example";

          instance.deleteJobGroup(username, password, jobgroupnamejobgroupID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.Success);
            expect(data.success).to.be.a('string');
            expect(data.success).to.be("true");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('editJobGroup', function() {
        it('should call editJobGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for editJobGroup call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var opts = {};
          opts.jobGroup = new ManageragentsApi.JobGroup();

          instance.editJobGroup(username, password, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.Success);
            expect(data.success).to.be.a('string');
            expect(data.success).to.be("true");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getJobGroup', function() {
        it('should call getJobGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for getJobGroup call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var jobgroupnamejobgroupID = "jobgroupnamejobgroupID_example";

          instance.getJobGroup(username, password, jobgroupnamejobgroupID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.JobGroupResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listJobGroups', function() {
        it('should call listJobGroups successfully', function(done) {
          // TODO: uncomment, update parameter values for listJobGroups call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";

          instance.listJobGroups(username, password, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.ListJobGroupsResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
