/*
 * Manager+Agents API
 * Signiant Manager+Agents provides a REST API to automate user management, user group, agent groups, jobs, resource controls, and job groups. 
 *
 * OpenAPI spec version: 14.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ManageragentsApi);
  }
}(this, function(expect, ManageragentsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ManageragentsApi.ObjectStorageProfilesApi();
  });

  describe('(package)', function() {
    describe('ObjectStorageProfilesApi', function() {
      describe('createObjectStorageProfile', function() {
        it('should call createObjectStorageProfile successfully', function(done) {
          // TODO: uncomment, update parameter values for createObjectStorageProfile call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var opts = {};
          opts.jSONForCreateLocalS3ObjectStorageProfileJSONForAzureStorageProfileIsInModelCreateAzureStorageProfileAndJSONForAWSS3StorageProfileIsInModelCreateAWSS3StorageProfile = new ManageragentsApi.StorageProfile();

          instance.createObjectStorageProfile(username, password, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.CreateObjectStorageResponse);
            expect(data.creator).to.be.a('string');
            expect(data.creator).to.be("admin");
            {
              let dataCtr = data.storageProfiles;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Object);
                expect(data).to.be();
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteStorageProfile', function() {
        it('should call deleteStorageProfile successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteStorageProfile call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var storageprofilenamestorageprofileID = "storageprofilenamestorageprofileID_example";

          instance.deleteStorageProfile(username, password, storageprofilenamestorageprofileID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.Success);
            expect(data.success).to.be.a('string');
            expect(data.success).to.be("true");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('editObjectStorageProfile', function() {
        it('should call editObjectStorageProfile successfully', function(done) {
          // TODO: uncomment, update parameter values for editObjectStorageProfile call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var opts = {};
          opts.jSONForEditLocalS3ObjectStorageProfile = new ManageragentsApi.EditS3StorageProfile();

          instance.editObjectStorageProfile(username, password, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.Success);
            expect(data.success).to.be.a('string');
            expect(data.success).to.be("true");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getListStorageProfiles', function() {
        it('should call getListStorageProfiles successfully', function(done) {
          // TODO: uncomment, update parameter values for getListStorageProfiles call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";

          instance.getListStorageProfiles(username, password, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.ListStorageProfiles);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getLocalS3StorageProfile', function() {
        it('should call getLocalS3StorageProfile successfully', function(done) {
          // TODO: uncomment, update parameter values for getLocalS3StorageProfile call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var storageprofilenamestorageprofileID = "storageprofilenamestorageprofileID_example";

          instance.getLocalS3StorageProfile(username, password, storageprofilenamestorageprofileID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.GetS3StorageProfile);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
