/*
 * Manager+Agents API
 * Signiant Manager+Agents provides a REST API to automate user management, user group, agent groups, jobs, resource controls, and job groups. 
 *
 * OpenAPI spec version: 14.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ManageragentsApi);
  }
}(this, function(expect, ManageragentsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ManageragentsApi.UserGroupsApi();
  });

  describe('(package)', function() {
    describe('UserGroupsApi', function() {
      describe('createUserGroup', function() {
        it('should call createUserGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for createUserGroup call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var opts = {};
          opts.userGroup = new ManageragentsApi.UserGroup();

          instance.createUserGroup(username, password, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.CreateUserGroupResponse);
            expect(data.creator).to.be.a('string');
            expect(data.creator).to.be("administrator");
            {
              let dataCtr = data.groups;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Object);
                expect(data).to.be();
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteUserGroup', function() {
        it('should call deleteUserGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteUserGroup call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var groupnamegroupID = "groupnamegroupID_example";

          instance.deleteUserGroup(username, password, groupnamegroupID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.Success);
            expect(data.success).to.be.a('string');
            expect(data.success).to.be("true");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('editUserGroup', function() {
        it('should call editUserGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for editUserGroup call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var opts = {};
          opts.userGroup = new ManageragentsApi.UserGroup();

          instance.editUserGroup(username, password, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.Success);
            expect(data.success).to.be.a('string');
            expect(data.success).to.be("true");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getUserGroup', function() {
        it('should call getUserGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for getUserGroup call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";
          var groupnamegroupID = "groupnamegroupID_example";

          instance.getUserGroup(username, password, groupnamegroupID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.UserGroupResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listUserGroups', function() {
        it('should call listUserGroups successfully', function(done) {
          // TODO: uncomment, update parameter values for listUserGroups call and complete the assertions
          /*
          var username = "username_example";
          var password = "password_example";

          instance.listUserGroups(username, password, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ManageragentsApi.ListUserGroupsResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
